groups:
  - name: miowsis_application
    interval: 30s
    rules:
      # Application availability
      - alert: ApplicationDown
        expr: up{job="miowsis-app"} == 0
        for: 5m
        labels:
          severity: critical
          service: miowsis
        annotations:
          summary: "MIOwSIS application is down"
          description: "The MIOwSIS application has been down for more than 5 minutes."
          
      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{job="miowsis-app",status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total{job="miowsis-app"}[5m]))
          ) > 0.05
        for: 10m
        labels:
          severity: warning
          service: miowsis
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 10 minutes. Current: {{ $value | humanizePercentage }}"
          
      # Slow response time
      - alert: SlowResponseTime
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket{job="miowsis-app"}[5m])) by (le)
          ) > 1
        for: 10m
        labels:
          severity: warning
          service: miowsis
        annotations:
          summary: "Slow response time detected"
          description: "95th percentile response time is above 1 second for the last 10 minutes. Current: {{ $value | humanizeDuration }}"
          
      # High request rate
      - alert: HighRequestRate
        expr: sum(rate(http_requests_total{job="miowsis-app"}[5m])) > 1000
        for: 5m
        labels:
          severity: info
          service: miowsis
        annotations:
          summary: "High request rate"
          description: "Request rate is above 1000 req/s for the last 5 minutes. Current: {{ $value | humanize }}"
          
      # Database connection issues
      - alert: DatabaseConnectionFailure
        expr: increase(database_connection_errors_total{job="miowsis-app"}[5m]) > 5
        for: 5m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection failures"
          description: "More than 5 database connection failures in the last 5 minutes"
          
      # Authentication failures
      - alert: HighAuthenticationFailureRate
        expr: |
          (
            sum(rate(auth_failures_total{job="miowsis-app"}[5m]))
            /
            sum(rate(auth_attempts_total{job="miowsis-app"}[5m]))
          ) > 0.1
        for: 10m
        labels:
          severity: warning
          service: auth
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is above 10% for the last 10 minutes"
          
      # Memory leak detection
      - alert: PotentialMemoryLeak
        expr: |
          (
            node_memory_MemAvailable_bytes{job="node-exporter"}
            /
            node_memory_MemTotal_bytes{job="node-exporter"}
          ) < 0.1
          and
          rate(node_memory_MemAvailable_bytes{job="node-exporter"}[1h]) < 0
        for: 30m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Potential memory leak detected"
          description: "Available memory is below 10% and decreasing over the last hour"