server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/miowsis_users}
    username: ${DATABASE_USERNAME:miowsis_user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: false
  kafka:
    # Disable Kafka completely for testing
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # Fail fast settings to prevent hanging
      properties:
        request.timeout.ms: 1000
        delivery.timeout.ms: 2000
        retries: 0
        max.block.ms: 1000
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.miowsis.*"

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.miowsis: INFO
    org.springframework.security: WARN
    org.springframework.cloud: WARN
    org.apache.kafka: WARN

# Disable Kafka for testing
miowsis:
  email:
    kafka:
      enabled: false
  events:
    kafka:
      enabled: false