spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    discovery:
      enabled: false
  
eureka:
  client:
    enabled: false

# Disable load balancing and use direct URLs
api-gateway:
  services:
    user-service-url: http://localhost:8081
    portfolio-service-url: http://localhost:8082
    ai-service-url: http://localhost:8083
    esg-service-url: http://localhost:8084