server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
        
        - id: portfolio-service
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/api/portfolio/**
          filters:
            - RewritePath=/api/portfolio/(?<segment>.*), /${segment}
        
        - id: trading-service
          uri: lb://TRADING-SERVICE
          predicates:
            - Path=/api/trading/**
          filters:
            - RewritePath=/api/trading/(?<segment>.*), /${segment}
        
        - id: esg-service
          uri: lb://ESG-SERVICE
          predicates:
            - Path=/api/esg/**
          filters:
            - RewritePath=/api/esg/(?<segment>.*), /${segment}
        
        - id: banking-service
          uri: lb://BANKING-SERVICE
          predicates:
            - Path=/api/banking/**
          filters:
            - RewritePath=/api/banking/(?<segment>.*), /${segment}
        
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>.*), /${segment}
        
        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/api/analytics/**
          filters:
            - RewritePath=/api/analytics/(?<segment>.*), /${segment}
        
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/ai/**
          filters:
            - RewritePath=/api/ai/(?<segment>.*), /${segment}
      
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            methods: GET,POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG