apiVersion: apps/v1
kind: Deployment
metadata:
  name: miowsis-app
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: miowsis
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_ENABLE_AI_ASSISTANT
          value: "true"
        - name: NEXT_PUBLIC_ENABLE_3D_VISUALIZATION
          value: "true"
        - name: NEXT_PUBLIC_ENABLE_GAMIFICATION
          value: "true"